news-FE/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace news_FE.Models
{
    public partial class Topic
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public int Parentid { get; set; }
        public int Orders { get; set; }
        public string Metakey { get; set; }
        public string Metadesc { get; set; }
        public DateTime Created_at { get; set; }
        public int Created_by { get; set; }
        public DateTime Updated_at { get; set; }
        public int Updated_by { get; set; }
        public int Status { get; set; }
    }
}

news-FE/Areas/Admin/Controllers/TopicsController.cs
using news_FE.consts;
using news_FE.library;
using news_FE.Models;
using news_FE.Request;
using news_FE.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace news_FE.Areas.Admin.Controllers
{
    public class TopicsController : BaseController
    {
        // GET: Admin/Topics

        public ActionResult Index()
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);

            var List = JsonConvert.DeserializeObject<List<Topic>>(getJsonRepons);

            return View(List);
        }
        public ActionResult Edit(int id)
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlFindTopicById + id, null);
            Topic List = JsonConvert.DeserializeObject<Topic>(getJsonRepons);

            string getJsonAllTopicRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);
            ViewBag.listtopic = JsonConvert.DeserializeObject<List<Topic>>(getJsonAllTopicRepons);
            return View(List);
        }

        [HttpPost]
        public ActionResult Edit(Topic topic)
        {
            JObject topicJson = new JObject
            {
                { "Id", topic.Id },
                { "Name", topic.Name },
                { "Slug", topic.Slug },
                { "Orders", topic.Orders },
                { "Metakey", topic.Metakey },
                { "Metadesc", topic.Metadesc },
                { "Created_at", topic.Created_at.ToString("yyyy-MM-ddTHH:mm:ss") },
                { "Created_by", topic.Created_by },
                { "Updated_at", topic.Updated_at.ToString("yyyy-MM-ddTHH:mm:ss")  },
                { "Updated_by", topic.Created_by},
                { "Status", topic.Status },
            };

            string EditResult = SendRequest.sendRequestPOSTwithJsonContent(ApiUrl.urlEditTopic, topicJson.ToString());
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(EditResult);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");

            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }

            return RedirectToAction("index");
        }

        public ActionResult Create()
        {
            string getJsonAllTopicRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);
            ViewBag.listtopic = JsonConvert.DeserializeObject<List<Topic>>(getJsonAllTopicRepons);
            return View();
        }
        [HttpPost]
        public ActionResult Create(Topic topic)
        {
            JObject topicJson = new JObject
            {
                { "Id", 0 },
                { "Name", topic.Name },
                { "Slug", "" },
                { "Orders", topic.Orders },
                { "Metakey", topic.Metakey },
                { "Metadesc", topic.Metadesc },
                { "Created_at", DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss") },
                { "Created_by", topic.Created_by },
                { "Updated_at", DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss")  },
                { "Updated_by", topic.Created_by},
            };
            string EditResult = SendRequest.sendRequestPOSTwithJsonContent(ApiUrl.urlCreateTopic, topicJson.ToString());
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(EditResult);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");

            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            return RedirectToAction("index");
        }
        public ActionResult Status(int Id, int Status)
        {

            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlChangeStatus + "?Id=" + Id + "&Status=" + Status, null);
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");

            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            return RedirectToAction("index");
        }
        public ActionResult DeTrash(int Id)
        {

            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlDeTrash+"?Id="+ Id, null);
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");
            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            return RedirectToAction("index");
        }
        public ActionResult reTrash(int Id)
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlReTrash + "?Id=" + Id, null);
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");
            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            return RedirectToAction("index");
        }
        public ActionResult delete(int Id)
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlDelete + "?Id=" + Id, null);
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");

            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            return RedirectToAction("index");
        }
        public ActionResult Trash()
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopicTrash, null);
            var List = JsonConvert.DeserializeObject<List<Topic>>(getJsonRepons); return View(List);
        }
    }
}

news-FE/Areas/Admin/Views/Topics/Create.cshtml
@model news_FE.Models.Topic

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@{
    List<SelectListItem> listcat = new List<SelectListItem>();
    List<SelectListItem> listorder = new List<SelectListItem>();
    List<SelectListItem> status = new List<SelectListItem>();
    SelectListItem statusitem1 = new SelectListItem() { Value = "1", Text = "Hiện" };
    SelectListItem statusitem2 = new SelectListItem() { Value = "2", Text = "Ẩn" };
    status.Add(statusitem1);
    status.Add(statusitem2);
    SelectListItem listorderitem;
    foreach (var item in ViewBag.listtopic)
    {
        listorderitem = new SelectListItem() { Value = item.Orders + "", Text = "Sau [" + item.Name + "]" };
        listorder.Add(listorderitem);


    }

}
<!-- Content Wrapper. Contains page content -->

<div class="card card-title bg-white p-1 container">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Thêm chủ đề bài viết</h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Bdmin">Home</a></li>
                <li class="breadcrumb-item active m-0">Thêm chủ đề bài viết</li>
            </ol>
        </div>
    </div>
</div>



<section class="container pt-2 card">
    @Html.Partial("_MessgeAlert")
    <div class=" bg-white p-4 ">

        @using (Html.BeginForm("Create", "topics"))
        {
            @Html.AntiForgeryToken()
            <div class=" row ">
                <div class="col-md-4">  </div>
                <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> THÊM LOẠI BÀI VIẾT</h3> </div>
                <div class="col-md-4 ">
                    <div class="float-right">
                        <button type="submit" class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                        <a href="~/Admin/Topics" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Hủy</a>
                    </div>
                </div>
            </div>
            <div class=" row ">
                <div class="col-md-8">
                    <div>
                        <label for="psw"><span class="text-secondary ">Tên chủ đề</span></label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Từ khóa SEO</span></label>
                        @Html.EditorFor(model => model.Metakey, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Metakey, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Mô tả SEO</span></label>
                        @Html.EditorFor(model => model.Metadesc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Metadesc, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">

                    <div>
                        <label for="psw"><span class="text-secondary ">Chọn vị trí hiển thị</span></label>
                        @Html.DropDownListFor(model => model.Orders, listorder, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Orders, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Trang Thái</span></label>
                        @Html.DropDownListFor(model => model.Status, status, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>


            </div>
        }
    </div>
</section>
<script>
    $("#topic").addClass("active");
</script>

news-FE/Areas/Admin/Views/Topics/Edit.cshtml
@model news_FE.Models.Topic
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    List<SelectListItem> listcat = new List<SelectListItem>();
    List<SelectListItem> listorder = new List<SelectListItem>();
    List<SelectListItem> status = new List<SelectListItem>();
    SelectListItem statusitem1 = new SelectListItem() { Value = "1", Text = "Hiện" };
    SelectListItem statusitem2 = new SelectListItem() { Value = "2", Text = "Ẩn " };
    status.Add(statusitem1);
    status.Add(statusitem2);
    SelectListItem listorderitem;
    foreach (var item in ViewBag.listtopic)
    {
        listorderitem = new SelectListItem() { Value = item.Orders + "", Text = "Sau [" + item.Name + "]" };
        listorder.Add(listorderitem);
    }
}
<!-- Content Wrapper. Contains page content -->
<div class="card card-title bg-white p-1 container">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Sửa chủ đề bài viết</h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Bdmin">Home</a></li>
                <li class="breadcrumb-item active m-0">Sửa chủ đề bài viết</li>
            </ol>
        </div>
    </div>
</div>


<section class="container card">
    @Html.Partial("_MessgeAlert")
    <div class=" bg-white p-4 ">
        @using (Html.BeginForm("Edit", "topics", new { id = "formTopicEdit" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Updated_at)
            @Html.HiddenFor(model => model.Updated_by)
            @Html.HiddenFor(model => model.Created_at)
            @Html.HiddenFor(model => model.Created_by)
            @Html.HiddenFor(model => model.Parentid)
            @Html.HiddenFor(model => model.Slug)
            <div class=" row ">
                <div class="col-md-4">  </div>
                <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success"> CHỈNH SỬA </h3> </div>
                <div class="col-md-4 ">
                    <div class="float-right">
                        <button type="submit" @*onclick="EditTopic()"*@ class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                        <a href="~/Admin/Topics" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Hủy</a>
                    </div>
                </div>
            </div>
            <div class=" row ">
                <div class="col-md-8">
                    <div>
                        <label for="psw"><span class="text-secondary ">Tên chủ đề</span></label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Từ khóa SEO</span></label>
                        @Html.EditorFor(model => model.Metakey, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Metakey, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Mô tả SEO</span></label>
                        @Html.EditorFor(model => model.Metadesc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Metadesc, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div>
                        <label for="psw"><span class="text-secondary ">Chọn vị trí hiển thị</span></label>
                        @Html.DropDownListFor(model => model.Orders, listorder, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Orders, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Trang Thái</span></label>
                        @Html.DropDownListFor(model => model.Status, status, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }
    </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $("#topic").addClass("active");

    function EditTopic() {
        var data = $("#formTopicEdit").serialize();
        $.ajax({
            type: "POST",
            data: JSON.stringify(data),
            url: "localhost:44313/api/Category/Edit",
            contentType: "application/json"
        }).done(function (data) {
            console.log('res', res);
            // Do something with the result :)
        });
    }
</script>

news-FE/Areas/Admin/Views/Topics/Index.cshtml
@{
    ViewBag.Title = "Quản lý chủ đề bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@model IEnumerable<news_FE.Models.Topic>
<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Quản lý chủ đề bài viết</h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Bdmin">Home</a></li>
                <li class="breadcrumb-item active m-0">Quản lý chủ đề bài viết</li>
            </ol>
        </div>
    </div>
</div>

<section class=" ">
    <div class=" bg-white card p-3 ">

        <div class="row">
            <div class="col-md-9  w-100 ">
            </div>
            <div class="col-md-3 ">
                <div class=" pt-1 ml-5">
                    <a title="Thêm bài loại viết" data-toggle="tooltip" data-placement="top" class="text-white btn-sm btn-success" href="~/Admin/Topics/Create">Add Topic <i class="fas fa-plus"></i></a>
                    <a title="Thùng rác" data-toggle="tooltip" data-placement="top" class="text-white btn-sm btn-danger " href="~/Admin/Topics/trash">Thùng rác<i class="fas fa-trash"></i></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9  w-100 ">
                @Html.Partial("_MessgeAlert")
            </div>
            <div class="col-md-12 p-3">

                <table id="myTable1" class="table  table-striped table-bordered dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th width="30%">Tên chủ đề</th>
                            <th width="20%">Link</th>
                            <th width="20%">Trạng thái</th>
                            <th width="20%">Chức Năng</th>
                            <th>ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td> <a class=" font-weight-bold card-link " href="">@item.Name</a></td>
                            <td> @Html.DisplayFor(modelItem => item.Slug)</td>

                            @if (item.Status == 1)
                            {
                                <th width="20%"> <span class="badge badge-success"> Hiển thị</span>  </th>
                            }
                            else
                            {
                                <th width="20%"><span class="badge badge-danger"> Đang ẩn</span> </th>
                            }
                            <td>
                                @if (item.Status == 1)
                                {
                                    <a title="Thay đổi trạng thái" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-success border a33" href="@Url.Action("Status", "topics", new { Id = item.Id , Status = item.Status })"> <i class="fas fa-toggle-on"></i> </a>
                                }
                                else
                                {
                                    <a title="Thay đổi trạng thái" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-danger border a33" href="@Url.Action("Status", "topics", new { id = item.Id  , Status = item.Status })"> <i class="fas fa-toggle-off"></i> </a>
                                }
                                <a title="Xóa vào thùng rác" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-danger border" href="@Url.Action("Detrash", "topics", new { id = item.Id })"> <i class="fas fa-trash-alt"></i></a>
                                <a title="Chỉnh sửa" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-warning border" href="@Url.Action("Edit", "topics", new { id = item.Id })">
                                    <i class="fas fa-edit"></i>
                                </a>
                            </td>
                            <td class="text-cam">@Html.DisplayFor(modelItem => item.Id)</td>
                        </tr>
                            }
                        </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<script>
    $("#topic").addClass("active");
</script>

news-FE/Areas/Admin/Views/Topics/Trash.cshtml
@model IEnumerable<news_FE.Models.Topic>
@{
    ViewBag.Title = "Trash";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Thùng rác chủ đề bài viết</h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Bdmin">Home</a></li>
                <li class="breadcrumb-item active m-0">Thùng rác chủ đề bài viết</li>
            </ol>
        </div>
    </div>
</div>

<section class=" ">
    <div class=" bg-white card p-3 ">

        <div class="row">
            <div class="col-md-9  w-100 ">
                @Html.Partial("_MessgeAlert")
            </div>
            <div class="col-md float-right">
                <div class=" pt-1 float-right">
                    <a title="Thoát" data-toggle="tooltip" data-placement="top"  class="text-white btn-sm btn-danger " href="~/Admin/Topics">Thoát </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9  w-100 ">
               
            </div>
            <div class="col-md-12 p-3">

                <table class="table px-3 table-striped table-bordered dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>Tên chủ đề</th>
                            <th>Link</th>
                            <th>Ngày Tạo</th>
                            <th>Trạng thái</th>
                            <th>Chức Năng</th>
                            <th>ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>

                            <td><a class=" font-weight-bold card-link " href=""> @Html.DisplayFor(modelItem => item.Name)</a></td>
                            <td> @Html.DisplayFor(modelItem => item.Slug)</td>
                            <td style="font-size:14px;">@item.Created_at.ToString("dd-MM-yyyy hh:mm:ss ")</td>
                            <th width="20%"><span class="badge badge-danger"> Đã xóa</span> </th>
                            <td>
                                <a title="Khôi phục" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-primary border " href="@Url.Action("Retrash", "Topics", new { id = item.Id })"> <i class="fas fa-undo"></i></a>
                                <a title="Xóa vĩnh viễn " data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-danger border" href="@Url.Action("Delete", "Topics", new { id = item.Id })">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </td>
                            <td class="text-cam ">@Html.DisplayFor(modelItem => item.Id)</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<script>
    $("#topic").addClass("active");

</script>