news-FE/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace news_FE.Models
{
    public partial class Post
    {
        public int ID { get; set; }
        public int Topid { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        public string Detail { get; set; }
        public string Img { get; set; }
        public string Type { get; set; }
        public string Metakey { get; set; }
        public string Metadesc { get; set; }
        public DateTime Created_at { get; set; }
        public int Created_by { get; set; }
        public DateTime Updated_at { get; set; }
        public int Updated_by { get; set; }
        public int Status { get; set; }
    }
}

news-FE/Areas/Admin/Controllers/PostsController.cs
using news_FE.consts;
using news_FE.library;
using news_FE.Models;
using news_FE.Request;
using news_FE.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace news_FE.Areas.Admin.Controllers
{
    public class PostsController : BaseController
    {
        // GET: Admin/Posts
        public ActionResult Index()
        {
            List<Post> ListPost = null;
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllPostAdmin, null);
            try
            {
                ListPost = JsonConvert.DeserializeObject<List<Post>>(getJsonRepons);
            }
            catch
            {
                var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
                Message.set_flash(objectResult.message.Message, "danger");
                return RedirectToAction("Unauthorized", "Auth");
            }
            if (ListPost != null)
            {
                return View(ListPost.OrderByDescending(m => m.ID));
            }
            else
            {
                Message.set_flash("Đã xảy ra lỗi", "danger");
                return RedirectToAction("Unauthorized", "Auth");
            }

        }
        public ActionResult Create()
        {
            string getJsonAllTopicRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);
            ViewBag.listtopic = JsonConvert.DeserializeObject<List<Topic>>(getJsonAllTopicRepons);
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Post post, HttpPostedFileBase file)
        {

            file = Request.Files["img"];
            string filename = file.FileName.ToString();
            if (filename.Equals("") == false)
            {
                string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlFindTopicById + post.Topid, null);
                Topic topic = JsonConvert.DeserializeObject<Topic>(getJsonRepons);
                string slug = Mystring.ToSlug(post.Title.ToString()) + DateTime.Now.ToString("-mmss");
                string namecate = Mystring.ToStringNospace(topic.Name);
                string ExtensionFile = Mystring.GetFileExtension(filename);
                string namefilenew = namecate + "/" + slug + "." + ExtensionFile;
                var path = Path.Combine(Server.MapPath("~/public/images/post"), namefilenew);
                var folder = Server.MapPath("~/public/images/post/" + namecate);
                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }
                file.SaveAs(path);
                post.Img = namefilenew;
            }
            else
            {
                post.Img = "please update picture";
            }
            post.Created_at = DateTime.Now;
            JObject PostJson = new JObject
            {
                { "Id", post.ID },
                { "Topid", post.Topid },
                { "Title", post.Title },
                { "Slug", "" },
                { "Detail", post.Detail },
                { "Img", post.Img },
                { "Type", post.Type },
                { "Metakey", post.Metakey },
                { "Metadesc", post.Metadesc  },
                { "Created_at", post.Created_at.ToString("yyyy-MM-ddTHH:mm:ss")},
                { "Created_by", post.Created_by},
                { "Updated_at", DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss")},
                { "Updated_by", post.Updated_by},
                { "Status", post.Status},
            };
            string EditResult = SendRequest.sendRequestPOSTwithJsonContent(ApiUrl.urlCreatePost, PostJson.ToString());
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(EditResult);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");
                return RedirectToAction("index");
            }
            else
            {

                Message.set_flash(objectResult.message.Message, "danger");

            }

            // call API all topic
            string getJsonAllTopicRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);
            ViewBag.listtopic = JsonConvert.DeserializeObject<List<Topic>>(getJsonAllTopicRepons);
            return View();
        }
        public ActionResult Edit(int id)
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlFindPostById + id, null);
            Post List = JsonConvert.DeserializeObject<Post>(getJsonRepons);
            string getJsonAllTopicRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);
            ViewBag.listtopic = JsonConvert.DeserializeObject<List<Topic>>(getJsonAllTopicRepons);
            return View(List);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Post post, HttpPostedFileBase file)
        {
            file = Request.Files["img"];
            string filename = file.FileName.ToString();
            if (filename.Equals("") == false)
            {
                string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlFindTopicById + post.Topid, null);
                Topic topic = JsonConvert.DeserializeObject<Topic>(getJsonRepons);
                string slug = Mystring.ToSlug(post.Title.ToString()) + DateTime.Now.ToString("-mmss");
                string namecate = Mystring.ToStringNospace(topic.Name);
                string ExtensionFile = Mystring.GetFileExtension(filename);
                string namefilenew = namecate + "/" + slug + "." + ExtensionFile;
                var path = Path.Combine(Server.MapPath("~/public/images/post"), namefilenew);
                var folder = Server.MapPath("~/public/images/post/" + namecate);
                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }
                file.SaveAs(path);
                post.Img = namefilenew;
            }
            post.Updated_at = DateTime.Now;
            JObject PostJson = new JObject
            {
                { "Id", post.ID },
                { "Topid", post.Topid },
                { "Title", post.Title },
                { "Slug", "" },
                { "Detail", post.Detail },
                { "Img", post.Img },
                { "Type", post.Type },
                { "Metakey", post.Metakey },
                { "Metadesc", post.Metadesc  },
                { "Created_at", post.Created_at.ToString("yyyy-MM-ddTHH:mm:ss")},
                { "Created_by", post.Created_by},
                { "Updated_at", post.Updated_at.ToString("yyyy-MM-ddTHH:mm:ss")},
                { "Updated_by", post.Updated_by},
                { "Status", post.Status},
            };
            string EditResult = SendRequest.sendRequestPOSTwithJsonContent(ApiUrl.urlEditPost, PostJson.ToString());
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(EditResult);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");
                return RedirectToAction("index");
            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            string getJsonAllTopicRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);
            ViewBag.listtopic = JsonConvert.DeserializeObject<List<Topic>>(getJsonAllTopicRepons);
            return View("");
        }
        public ActionResult Status(int Id, int Status)
        {

            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlChangeStatusPost + "?Id=" + Id + "&Status=" + Status, null);
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");
                return RedirectToAction("index");
            }
            else
            {

                Message.set_flash(objectResult.message.Message, "danger");

            }
            return RedirectToAction("index");
        }
        public ActionResult DeTrash(int Id)
        {

            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlDeTrashPost + "?Id=" + Id, null);
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");

            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            return RedirectToAction("index");
        }
        public ActionResult reTrash(int Id)
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlReTrashPost + "?Id=" + Id, null);
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");

            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            return RedirectToAction("index");
        }
        public ActionResult delete(int Id)
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlDeletePost + "?Id=" + Id, null);
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Post>>(getJsonRepons);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");

            }
            else

news-FE/Areas/Admin/Views/Posts/Create.cshtml
@model news_FE.Models.Post
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@{
    List<SelectListItem> listcat = new List<SelectListItem>();
    List<SelectListItem> listorder = new List<SelectListItem>();
    List<SelectListItem> status = new List<SelectListItem>();

    SelectListItem statusitem1 = new SelectListItem() { Value = "1", Text = "Xuẩt Bản" };
    SelectListItem statusitem2 = new SelectListItem() { Value = "2", Text = "Chưa Xuất bản" };
    status.Add(statusitem1);
    status.Add(statusitem2);

    SelectListItem listcatitem;
    foreach (var item in ViewBag.listTopic)
    {
        listcatitem = new SelectListItem() { Value = item.Id + "", Text = item.Name + "" };
        listcat.Add(listcatitem);
    }

}
<!-- Content Wrapper. Contains page content -->
<div class="card card-title bg-white p-1 container">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Thêm bài viết</h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Bdmin">Home</a></li>
                <li class="breadcrumb-item active m-0">Thêm bài viết</li>
            </ol>
        </div>
    </div>
</div>


<section class="container pt-2 card">
    @Html.Partial("_MessgeAlert")
    <div class="container bg-white pt-4 ">

        @using (Html.BeginForm("Create", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class=" row ">
                <div class="col-md-4">  </div>
                <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> THÊM BÀI VIẾT</h3> </div>
                <div class="col-md-4 ">
                    <div class="float-right">
                        <button type="submit" class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                        <a href="~/Bdmin/post" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Hủy</a>
                    </div>
                </div>
            </div>
            <div class=" row ">
                <div class="col-md-8">
                    <div>
                        <label for="psw"><span class="text-secondary ">Tiêu đề bài viết</span></label>
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                  
                    <div>
                        <label for="psw"><span class="text-secondary ">Nội dung bài viết</span></label>
                        @Html.TextAreaFor(model => model.Detail, new
                        {
                            @class = "form-control textarea",
                       @style = "width: 100%;font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"
                        })
                        @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div>
                        <label for="psw"><span class="text-secondary ">Từ khóa SEO</span></label>
                        @Html.EditorFor(model => model.Metakey, new { htmlAttributes = new { @class = "form-control " } })
                        @Html.ValidationMessageFor(model => model.Metakey, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Mô ta SEO</span></label>
                        @Html.EditorFor(model => model.Metadesc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Metadesc, "", new { @class = "text-danger" })
                    </div>
                    <label for="psw"><span class="text-secondary ">Chọn loại Loại Bài viết</span></label>
                    <div>
                        @Html.DropDownListFor(model => model.Topid, listcat, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Topid, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Hình ảnh Bài viết</span></label>
                        <input type="file" class="form-control" name="img" />
                        @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })

                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Trang Thái</span></label>
                        @Html.DropDownListFor(model => model.Status, status, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })

                    </div>
                </div>
            
            </div>
        }
    </div>
</section>
<script>
    $("#post").addClass("active");
    $(function () {
        // Summernote
        $('.textarea').summernote()
    })
</script>

news-FE/Areas/Admin/Views/Posts/Edit.cshtml
@model news_FE.Models.Post
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    List<SelectListItem> listcat = new List<SelectListItem>();
    List<SelectListItem> listorder = new List<SelectListItem>();
    List<SelectListItem> status = new List<SelectListItem>();

    SelectListItem statusitem1 = new SelectListItem() { Value = "1", Text = "Xuẩt Bản" };
    SelectListItem statusitem2 = new SelectListItem() { Value = "2", Text = "Chưa Xuất bản" };
    status.Add(statusitem1);
    status.Add(statusitem2);



    SelectListItem listcatitem;
    foreach (var item in ViewBag.listTopic)
    {
        listcatitem = new SelectListItem() { Value = item.Id + "", Text = item.Name + "" };
        listcat.Add(listcatitem);
    }

}
<!-- Content Wrapper. Contains page content -->
<div class="card card-title bg-white p-1 container">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Sửa bài viết</h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Bdmin">Home</a></li>
                <li class="breadcrumb-item active m-0">Sửa bài viết</li>
            </ol>
        </div>
    </div>
</div>

<!-- /.content-header -->


<section class="pt-2 container card">
    @Html.Partial("_MessgeAlert")
    <div class="container bg-white p-4 ">

        @using (Html.BeginForm("Edit", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.Created_at)
            @Html.HiddenFor(model => model.Created_by)
            @Html.HiddenFor(model => model.Img)
            @Html.HiddenFor(model => model.Type)
            <div class=" row ">
                <div class="col-md-4">  </div>
                <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> CẬP NHẬT BÀI VIẾT</h3> </div>
                <div class="col-md-4 ">
                    <div class="float-right">
                        <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                        <a href="~/Bdmin/post" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Hủy</a>
                    </div>
                </div>
            </div>
            <div class=" row ">
                <div class="col-md-8">
                    <div>
                        <label for="psw"><span class="text-secondary ">Tiêu đề bài viết</span></label>
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control ckeditor" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Nội dung bài viết</span></label>
                        @Html.TextAreaFor(model => model.Detail, new
                        {
                            @class = "form-control textarea",
                       @style = "width: 100%;font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"
                        })
                        @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="col-md-4">
                    <div>
                        <label for="psw"><span class="text-secondary ">Từ khóa SEO</span></label>
                        @Html.EditorFor(model => model.Metakey, new { htmlAttributes = new { @class = "form-control ckeditor" } })
                        @Html.ValidationMessageFor(model => model.Metakey, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Mô ta SEO</span></label>
                        @Html.EditorFor(model => model.Metadesc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Metadesc, "", new { @class = "text-danger" })
                    </div>
                    <label for="psw"><span class="text-secondary ">Chọn loại Loại Bài viết</span></label>
                    <div>
                        @Html.DropDownListFor(model => model.Topid, listcat, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Topid, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Hình ảnh Bài viết</span></label>
                        <input type="file" class="form-control" name="img" />
                        @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary ">Trang Thái</span></label>
                        @Html.DropDownListFor(model => model.Status, status, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                    <div class="p-3 ">
                        <h4>Bình luận</h4>                                                 
                       @Html.Action("_getAllComment", "Posts",new { Id = Model.ID})
                    </div>
                </div>
            </div>
        }

    </div>
</section>
<script>
    $("#post").addClass("active");
    $(function () {
        // Summernote
        $('.textarea').summernote()
    })
</script>

news-FE/Areas/Admin/Views/Posts/Index.cshtml
@{
    ViewBag.Title = "Quản lý bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@model IEnumerable<news_FE.Models.Post>
<!-- Content Wrapper. Contains page content -->
<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Quản lý bài viết</h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Admin">Home</a></li>
                <li class="breadcrumb-item active m-0">Quản lý loại bài viết</li>
            </ol>
        </div>
    </div>
</div>

<section class=" ">
    <div class=" bg-white card p-3 ">

        <div class="row">
            <div class="col-md  w-100 ">
                @Html.Partial("_MessgeAlert")
            </div>
            <div class="col-md ">
                <div class=" pt-1 ml-5 float-right">
                    <a  title="Thêm bài viết" data-toggle="tooltip" data-placement="top" class="text-white btn-sm btn-success" href="~/Admin/Posts/Create">Thêm bài viết <i class="fas fa-plus"></i></a>
                    <a  title="Thùng rác" data-toggle="tooltip" data-placement="top" class="text-white btn-sm btn-danger " href="~/Admin/Posts/trash">Thùng rác<i class="fas fa-trash"></i></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9  w-100 ">
                @*@Html.Partial("_MessgeAlert")*@
            </div>
            <div class="col-md-12 p-3">

                <table id="myTable1" class="table  table-striped table-bordered dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>Hình ảnh</th>
                            <th>Tên bài viết</th>
                            <th>Chủ đề</th>
                            <th>Ngày Tạo</th>
                            <th>Chức Năng</th>
                            <th>ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            string title = item.Title;
                            <tr>

                                <td><img width="50" src="~/public/images/post/@Html.DisplayFor(modelItem => item.Img)"></td>
                                <td>
                                    @if (title.Length > 50)
                                    {
                                        <a class=" font-weight-bold card-link " href="">@title.Substring(0, 50) ...</a>

                                    }
                                    else
                                    {
                                        <a class=" font-weight-bold card-link " href="">@title </a>
                                    }

                                </td>
                                <td width="15%">  @Html.DisplayFor(modelItem => item.Topid)</td>
                                <td style="font-size:14px;">@item.Created_at.ToString("dd/MM/yyyy hh:mm tt")</td>
                                <td>
                                    @if (item.Status == 1)
                                    {
                                        <a  title="Thay đổi trạng thái" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-success border a33" href="@Url.Action("Status", "posts", new { id = item.ID,Status = item.Status })"> <i class="fas fa-toggle-on"></i> </a>
                                    }
                                    else
                                    {
                                        <a  title="Thay đổi trạng thái" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-danger border a33" href="@Url.Action("Status", "posts", new { id = item.ID,Status =item.Status })"> <i class="fas fa-toggle-off"></i> </a>
                                    }
                                    <a  title="Xóa vào thùng rác" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-danger border" href="@Url.Action("Detrash", "posts", new { id = item.ID })"> <i class="fas fa-trash-alt"></i></a>
                                    <a  title="Chỉnh sửa" data-toggle="tooltip" data-placement="top" class="btn btn-sm btn-light text-warning border" href="@Url.Action("Edit", "posts", new { id = item.ID })">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td class="text-cam">@Html.DisplayFor(modelItem => item.ID)</td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</section>
<script>
                $("#post").addClass("active");
</script>

news-FE/Areas/Admin/Views/Posts/_getAllSubComment.cshtml
@model  IEnumerable<news_FE.Models.Comment>

@foreach (var item in Model)
{
    if (item.Status == 1)
    {
        <div class="geser " >
            <div class="media">
                <div class="media-left">
                    <img src="https://i.ebayimg.com/images/g/vrAAAOSwpDdVU7C6/s-l400.jpg" class="media-object" style="width:40px">
                </div>
                <div class="media-body ml-3">
                    <a href="@Url.Action("ChangeStatusHidenShowComment", "Posts", new { id = item.Id,status = item.Status, postId = item.PostId })" class="btn btn-sm  float-right "><i class="fas fa-eye text-info"></i></a>
                    <h4 class="media-heading title text-warning m-0">@item.Name</h4>
                    <span style="font-size:12px;" class="m-0 text-success">lúc: @item.Create_at.ToString("dd-MM-yyyy hh:mm:ss")</span>
                    <p class="komen">
                        @item.CommentDetail<br>
                    </p>

                </div>
            </div>
        </div>
    }
    else
    {
        <div class="geser " style="opacity:0.4;">
            <div class="media">
                <div class="media-left">
                    <img src="https://i.ebayimg.com/images/g/vrAAAOSwpDdVU7C6/s-l400.jpg" class="media-object" style="width:40px">
                </div>
                <div class="media-body ml-3">
                    <a href="@Url.Action("ChangeStatusHidenShowComment", "Posts", new { id = item.Id,status = item.Status, postId = item.PostId })" class="btn btn-sm  float-right " ><i class="fas fa-eye-slash text-danger"></i></a>
                    <h4 class="media-heading title text-warning m-0">@item.Name</h4>
                    <span style="font-size:12px;" class="m-0 text-success">lúc: @item.Create_at.ToString("dd-MM-yyyy hh:mm:ss")</span>
                    <p class="komen">
                        @item.CommentDetail<br>
                    </p>

                </div>
            </div>
        </div>
    }
}

news-FE/Areas/Admin/Views/Posts/getAllComment.cshtml
@model  IEnumerable<news_FE.Models.Comment>

@foreach (var item in Model)
{
    if (item.Status == 1)
    {
        <div class="media ">
            <div class="media-left">
                <img src="https://i.ebayimg.com/images/g/vrAAAOSwpDdVU7C6/s-l400.jpg" class="media-object" style="width:40px">
            </div>
            <div class="media-body ml-3">
                <a href="@Url.Action("ChangeStatusHidenShowComment", "Posts", new { id = item.Id,status = item.Status, postId = item.PostId })" class="btn btn-sm  float-right "><i class="fas fa-eye text-info"></i></a>
                <h4 class="media-heading title m-0">@item.Name</h4>
                <span style="font-size:12px;" class="m-0 text-success">lúc: @item.Create_at.ToString("dd-MM-yyyy hh:mm:ss")</span>
                <p class="komen">
                    @item.CommentDetail<br>
                </p>
            </div>
        </div>
    }
    else
    {
        <div class="media " style="opacity:0.4;">
            <div class="media-left">
                <img src="https://i.ebayimg.com/images/g/vrAAAOSwpDdVU7C6/s-l400.jpg" class="media-object" style="width:40px">
            </div>
            <div class="media-body ml-3">
                <a href="@Url.Action("ChangeStatusHidenShowComment", "Posts", new { id = item.Id,status = item.Status, postId = item.PostId })" class="btn btn-sm  float-right "><i class="fas fa-eye-slash text-danger"></i></a>
                <h4 class="media-heading title m-0">@item.Name</h4>
                <span style="font-size:12px;" class="m-0 text-success">lúc: @item.Create_at.ToString("dd-MM-yyyy hh:mm:ss")</span>
                <p class="komen">
                    @item.CommentDetail<br>
                </p>
            </div>
        </div>
    }
    @Html.Action("_getAllSubComment", "Posts", new { Id = item.PostId, parintId = item.Id })
}
<style>
    .title {
        font-size: 14px;
        font-weight: bold;
    }

    .komen {
        font-size: 14px;
    }

    .geser {
        margin-left: 55px;
        margin-top: 5px;
    }
</style>