news-FE/Controllers/ModulesController.cs
using news_FE.consts;
using news_FE.library;
using news_FE.Models;
using news_FE.Request;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace news_FE.Controllers
{
    public class ModulesController : Controller
    {
        // GET: Modules
        public ActionResult _PostSuggest()
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllPost, null);
            var ListPost = JsonConvert.DeserializeObject<List<Post>>(getJsonRepons)
                .Where(m=>m.Status==1).OrderBy(m=>Guid.NewGuid()).ToList().Take(2);       
            return View("_PostSuggest", ListPost);
        }
        public ActionResult _allCategory()
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);
            var ListCate = JsonConvert.DeserializeObject<List<Topic>>(getJsonRepons).OrderBy(m => m.Id);
            return View("_allCategory", ListCate);
        }
        public ActionResult _CategoryInMenu()
        {
            string getJsonRepons = SendRequest.sendRequestGET(ApiUrl.urlGetAllTopic, null);
            var ListCate = JsonConvert.DeserializeObject<List<Topic>>(getJsonRepons).OrderBy(m => m.Id).Take(8);
            return View("_CategoryInMenu", ListCate);
        }
        public ActionResult _getAllComment(int id, string slug)
        {
            ViewBag.slug = slug;
            string getJsonReponsComment = SendRequest.sendRequestGET(ApiUrl.urlGetAllComment + id, null);
            var list = JsonConvert.DeserializeObject<List<Comment>>(getJsonReponsComment)
                .Where(m => m.Status == 1)
                .Where(m => m.ParentId == 0).OrderByDescending(m=>m.Create_at);
            return View("_getAllComment", list);
        }
        public ActionResult _getAllSubComment(int id, int parintId,string slug)
        {
            ViewBag.slug = slug;
            ViewBag.parintId = parintId;
            string getJsonReponsComment = SendRequest.sendRequestGET(ApiUrl.urlGetAllComment + id, null);
            var list = JsonConvert.DeserializeObject<List<Comment>>(getJsonReponsComment)
                .Where(m => m.ParentId != 0 && m.ParentId == parintId)
                .Where(m=>m.Status==1)
                .OrderByDescending(m=>m.Create_at);
            return View("_getAllSubComment", list);
        }
        [HttpPost]
        public ActionResult sendCommentSub(Comment comment, string slug)
        {
            JObject topicJson = new JObject
            {
                { "Id", 0 },
                { "PostId", comment.PostId },
                { "parentId", comment.ParentId },
                { "commentDetail", comment.CommentDetail },
                { "name", comment.Name },
                { "Star", 3 },
                { "Create_at", DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss") },
                { "Status", 1 },
            };
            // viết thêm đoạn này
            string EditResult = SendRequest.sendRequestPOSTwithJsonContent(ApiUrl.urlCreateComment, topicJson.ToString());
            var objectResult = JsonConvert.DeserializeObject<ObjectResult<Comment>>(EditResult);
            if (objectResult.code == 200)
            {
                Message.set_flash(objectResult.message.Message, "success");
            }
            else
            {
                Message.set_flash(objectResult.message.Message, "danger");
            }
            return RedirectToAction("PostDetail", "Site", new { slug = slug });

        }
    }
}

news-FE/Views/Modules/_CategoryInMenu.cshtml
@model IEnumerable<news_FE.Models.Topic>
@{
    Layout = null;
}
@foreach (var item in Model)
{
    <li class="nav-item">
        <a class="nav-link" href="~/@item.Slug">@item.Name</a>
    </li>
}

news-FE/Views/Modules/_PostSuggest.cshtml
@model IEnumerable<news_FE.Models.Post>
@{
    Layout = null;
}
@foreach (var item in Model)
{
    <ul class="list-unstyled  border-top pt-3">
        <li><img width="430" src="~/public/images/post/@item.Img" alt=""></li>
        <li class="pl-3 row">
            <a class="card-link text-dark" href="~/chi-tiet-bai-viet/@item.Slug">
                @if (item.Title.Length > 70)
                {
                    <span class="font-weight-bold " style="font-size:25px;">@item.Title.Substring(0, 70) ....</span>
                }
                else
                {
                    <span class="font-weight-bold " style="font-size:25px;">@item.Title</span>
                }
            </a>
            <br />
            <span style="font-size:12px;" class="text-info"><i class="far fa-clock"></i> @item.Created_at</span>
        </li>

    </ul>
}

news-FE/Views/Modules/_allCategory.cshtml
@model IEnumerable<news_FE.Models.Topic>
    @{ 
        Layout = null;
    }
<ul class="list-group bg-white">
    <li class="list-group-item bg-light"><h6 class="font-weight-bold text-xanh "><i class="far fa-folder-open"></i> DANH MỤC BÀI VIẾT</h6></li>
    @foreach (var item in Model)
    {
        <li class="list-group-item"><a class="card-link text-body1" href="~/@item.Slug">@item.Name</a></li>
    }

</ul>

news-FE/Views/Modules/_getAllComment.cshtml
@model  IEnumerable<news_FE.Models.Comment>
@{
    Layout = null;
}
@foreach (var item in Model)
{
    var name = '@' + item.Name;
    <div class="media ">
        <div class="media-left">
            <img src="https://i.ebayimg.com/images/g/vrAAAOSwpDdVU7C6/s-l400.jpg" class="media-object" style="width:40px">
        </div>
        <div class="media-body ml-3">
            <h4 class="media-heading title m-0">@item.Name</h4>
            <span style="font-size:12px;" class="m-0 text-success">lúc: @item.Create_at.ToString("dd-MM-yyyy hh:mm:ss")</span>
            <p class="komen">
                @item.CommentDetail<br> 
                <a data-toggle="collapse" href="#collapseExample_@item.Id" role="button" aria-expanded="false">Trả lời</a>
            </p>
            <div class="collapse" id="collapseExample_@item.Id">
                <form class="form-inline "  action="~/Site/sendComment" method="post">
                    <input type="hidden" name="PostId" value="@item.PostId" />
                    <input type="hidden" name="parentId" value="@item.Id" />
                    <input type="text" class="form-control" placeholder="tên bạn" name="name" value="" required/>
                    <input type="hidden" name="slug" value="@ViewBag.slug" />
                    <div class="form-group">
                        <textarea rows="2" name="CommentDetail" class="form-control" required> @name.Replace(" ", "")  </textarea>
                        <button type="submit" class="btn btn-sm btn-primary mb-2 "><i class="fas fa-paper-plane"></i></button>
                    </div>
                </form>
            </div>

        </div>
    </div>
     
    @Html.Action("_getAllSubComment", "Modules", new { Id = item.PostId, parintId = item.Id,slug = @ViewBag.slug })
}
  

news-FE/Views/Modules/_getAllSubComment.cshtml
@model  IEnumerable<news_FE.Models.Comment>
@{
    Layout = null;
}
@foreach (var item in Model)
{
    var name = '@' + item.Name;
    <div class="geser ">
        <div class="media">
            <div class="media-left">
                <img src="https://i.ebayimg.com/images/g/vrAAAOSwpDdVU7C6/s-l400.jpg" class="media-object" style="width:40px">
            </div>
            <div class="media-body ml-3">

                <h4 class="media-heading title text-warning m-0">@item.Name</h4>
                <span style="font-size:12px;" class="m-0 text-success">lúc: @item.Create_at.ToString("dd-MM-yyyy hh:mm:ss")</span>
                <p class="komen">
                    @item.CommentDetail<br>
                    <a data-toggle="collapse" href="#collapseExample_@item.Id" role="button" aria-expanded="false">Trả lời</a>
                </p>
                <div class="collapse" id="collapseExample_@item.Id">
                    <form class="form-inline" name="sub" action="~/Site/sendComment" method="post">
                        <input type="hidden" name="PostId" value="@item.PostId" />
                        <input type="hidden" name="parentId" value="@ViewBag.parintId" />
                        <input type="text" class="form-control" placeholder="tên bạn" name="name" value="" required />
                        <input type="hidden" name="slug" value="@ViewBag.slug" />
                        <div class="form-group">
                            <textarea rows="2" name="CommentDetail" class="form-control" required> @name.Replace(" ", "")  </textarea>
                            <button type="submit" class="btn btn-sm btn-primary mb-2 "><i class="fas fa-paper-plane"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

}